export const HATCHING_CONSTS = {
	MIN_LINE_SIZE: 1,
	MAX_LINE_SIZE: 100,

	MIN_SPACING: 1,
	MAX_SPACING: 100,

	DEFAULT_LINE_SIZE: 4,
	DEFAULT_SPACING: 16,

	DEFAULT_LINE_COLOR: "#ffffff",
	DEFAULT_BG_COLOR: "#0064fc",

	DEFAULT_WITH_VARS: true,
	DEFAULT_RIGHT_LEANING: true,
	DEFAULT_CROSS_HATCHING: false,
};
