export const POLKA_DOTS_CONSTS = {
	MIN_DOT_SIZE: 2,
	MAX_DOT_SIZE: 250,

	MIN_SPACING: 0,
	MAX_SPACING: 250,

	DEFAULT_DOT_SIZE: 12,
	DEFAULT_SPACING: 24,

	DEFAULT_DOT_COLOR: "#ffffff",
	DEFAULT_BG_COLOR: "#0064fc",
	DEFAULT_WITH_VARS: true,
	DEFAULT_HEX: true,
};
