export const GRID_PATTERN_CONSTS = {
	MIN_LINE_SIZE: 1,
	MAX_LINE_SIZE: 250,

	MIN_SPACING: 0,
	MAX_SPACING: 250,

	DEFAULT_LINE_SIZE: 6,
	DEFAULT_SPACING: 16,

	DEFAULT_LINE_COLOR: "#ffffff",
	DEFAULT_BG_COLOR: "#0064fc",
	DEFAULT_WITH_VARS: true,
};
